name: Check formatting

on:
  push:
    branches:
      - master
    paths:
      - "**.nix"
      - .github/workflows/fmt.yml
  pull_request:
    branches:
      - master
    paths:
      - "**.nix"
      - .github/workflows/fmt.yml
  workflow_dispatch:

jobs:
  fmt:
    uses: ./.github/workflows/prelude.yml
    with:
      command: nix fmt -- --ci
      cachix: false
