name: Check formatting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  fmt:
    uses: ./.github/workflows/prelude.yml
    with:
      command: nix fmt -- --ci
