name: Prelude

on:
  workflow_call:
    inputs:
      platform:
        default: "ubuntu"
        required: false
        type: string

      command:
        required: false
        type: string

      cachix:
        default: true
        required: false
        type: boolean

    secrets:
      CACHIX_AUTH_TOKEN:
        required: false

jobs:
  prelude:
    runs-on: "${{ inputs.platform }}-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            experimental-features = nix-command flakes

      - name: Setup cachix
        if: ${{ inputs.cachix }}
        uses: cachix/cachix-action@v17
        with:
          name: widici-nix-config
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run command ${{ inputs.command }}
        if: ${{ inputs.command != '' }}
        run: "${{ inputs.command }}"
